# Generated by Django 3.0.3 on 2020-02-27 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
