# Generated by Django 3.0.3 on 2020-02-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default='default', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='profession',
            field=models.CharField(default='default', max_length=200),
        ),
    ]
