# Generated by Django 3.0.3 on 2020-04-01 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='PDFFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdffile', models.FileField(blank=True, null=True, upload_to='')),
                ('disability', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disability.Disability')),
            ],
        ),
        migrations.AddField(
            model_name='disability',
            name='tags',
            field=models.ManyToManyField(to='disability.Keyword'),
        ),
    ]
