# Generated by Django 3.0.3 on 2020-04-13 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_disability_description'),
        ('children', '0002_auto_20200413_0203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='children',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='children',
            name='disability',
        ),
        migrations.AddField(
            model_name='children',
            name='disabilities',
            field=models.ManyToManyField(blank=True, null=True, related_name='child_disabilities', to='posts.Disability'),
        ),
    ]
