# Generated by Django 2.1.7 on 2020-03-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpiderFetch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfDisease', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('keyword', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'the links',
            },
        ),
    ]
