# Generated by Django 2.1.7 on 2020-03-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80)),
                ('type', models.CharField(max_length=30)),
                ('degre', models.CharField(max_length=6, null=True)),
                ('brasserie', models.CharField(max_length=80)),
            ],
        ),
    ]
