# Generated by Django 2.1.7 on 2020-03-22 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0002_beer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Beer',
        ),
    ]
