# Generated by Django 2.1.7 on 2020-03-26 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0004_blogpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
