# Generated by Django 2.1.7 on 2020-04-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0005_delete_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameDisease', models.CharField(max_length=200)),
                ('urllink', models.URLField()),
            ],
        ),
    ]
