# Generated by Django 3.0.3 on 2020-03-30 14:15

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('metadata', '0006_fetcheddata_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='fetcheddata',
            name='keywords',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
