# Generated by Django 3.0.3 on 2020-03-21 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0037_auto_20200315_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('ageRange', models.CharField(max_length=100)),
                ('pdf', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='posts.PDF')),
            ],
        ),
    ]
