# Generated by Django 3.0.3 on 2020-04-10 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_auto_20200409_0817'),
        ('timeline', '0002_auto_20200409_1936'),
    ]

    operations = [
    ]
