# Generated by Django 3.0.3 on 2020-03-21 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0037_auto_20200315_1013'),
        ('timeline', '0002_auto_20200321_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeline',
            name='pdf',
        ),
        migrations.AddField(
            model_name='timeline',
            name='pdfs',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='posts.PDF'),
        ),
    ]
