# Generated by Django 3.0.3 on 2020-04-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_merge_20200410_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='age',
            field=models.CharField(choices=[('0-4', '0-4'), ('4-11', '4-11'), ('11-18', '11-18'), ('18-25', '18-25')], max_length=6),
        ),
    ]
