# Generated by Django 3.0.3 on 2020-04-08 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_timeline_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeline',
            name='user',
        ),
    ]
