# Generated by Django 3.0.3 on 2020-04-12 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0005_auto_20200412_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='header',
            field=models.CharField(choices=[('Financial Support', 'Financial Support'), ('Educational Support', 'Educational Support'), ('Governmental Support', 'Governmental Support '), ('Charity Support Groups', 'Charity Support Groups'), ('Therapy Support', 'Therapy Support '), ('Transport Support', 'Transport Support ')], max_length=30),
        ),
    ]
