# Generated by Django 3.0.3 on 2020-03-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0037_auto_20200315_1013'),
        ('timeline', '0006_auto_20200321_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeline',
            name='pdf',
        ),
        migrations.AddField(
            model_name='timeline',
            name='pdf',
            field=models.ManyToManyField(default=None, related_name='timelines', to='posts.PDF'),
        ),
    ]
