# Generated by Django 3.0.3 on 2020-04-12 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200410_0951'),
        ('timeline', '0006_auto_20200412_0407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeline',
            name='pdfs',
        ),
        migrations.AddField(
            model_name='timeline',
            name='content',
            field=models.ManyToManyField(to='posts.Content'),
        ),
    ]
