# Generated by Django 2.1.3 on 2020-03-29 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0009_auto_20200324_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='timelinepdfs')),
            ],
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='pdf',
        ),
        migrations.AlterField(
            model_name='timeline',
            name='age',
            field=models.CharField(choices=[('0-4', '0-4'), ('4-11', '4-11'), ('11-18', '11-18'), ('18-25', '18-25')], max_length=6),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='header',
            field=models.CharField(choices=[('Financial Support', 'Financial Support'), ('Educational Support', 'Educational Support'), ('Governmental Support', 'Governmental Support '), ('Charity Support Groups', 'Charity Support Groups'), ('Therapy Support', 'Therapy Support '), ('Transport Support', 'Transport Support ')], max_length=30),
        ),
        migrations.AddField(
            model_name='pdf',
            name='timeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeline.Timeline'),
        ),
    ]
