# Generated by Django 3.0.3 on 2020-04-13 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0002_auto_20200413_0203'),
        ('timeline', '0009_auto_20200412_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='children.Children'),
        ),
    ]
