# Generated by Django 2.1.3 on 2020-03-30 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0001_initial'),
        ('timeline', '0010_auto_20200329_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='child',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='children.Children'),
            preserve_default=False,
        ),
    ]
