# Generated by Django 3.0.3 on 2020-04-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_data', '0003_pagelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagelink',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
