# Generated by Django 3.0.3 on 2020-04-06 18:51

from django.db import migrations


class Migration(migrations.Migration):

    def addData(apps, schema_editor):
        data = [

            ]
        User = apps.get_model("auth", "User")
        PDF = apps.get_model("posts", "PDF")
        p = PDF(title="Test PDF title", content="Test PDF content", author = User.objects.first(), lower_age = 0, upper_age = 4, pdf_file="resources/pdfs/test_iD2LEKW.pdf")
        p.save()

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
            migrations.RunPython(addData),
    ]
