# Generated by Django 3.0.3 on 2020-04-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200409_0333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf',
            name='age_group',
        ),
        migrations.RemoveField(
            model_name='video',
            name='age_group',
        ),
        migrations.AddField(
            model_name='content',
            name='age_group',
            field=models.CharField(choices=[('0-4', '0-4'), ('4-11', '4-11'), ('11-18', '11-18'), ('18-25', '18-25'), ('N/A', 'N/A')], default='N/A', max_length=20),
        ),
    ]
