# Generated by Django 3.0.3 on 2020-04-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200409_0817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Disabilities',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='content',
            name='disabilities',
            field=models.ManyToManyField(blank=True, null=True, related_name='disabilities', to='posts.Disability'),
        ),
    ]
