# Generated by Django 3.0.3 on 2020-04-08 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200406_1856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['-date_posted']},
        ),
        migrations.AlterField(
            model_name='content',
            name='topics',
            field=models.ManyToManyField(blank=True, null=True, related_name='topics', to='posts.Topic'),
        ),
    ]
