# Generated by Django 3.0.3 on 2020-04-13 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_content_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='disability',
            name='description',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
