# Generated by Django 3.0.3 on 2020-02-26 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20200226_1916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='topic',
        ),
    ]
