# Generated by Django 3.0.3 on 2020-04-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20200413_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='pdf_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
