# Generated by Django 3.0.3 on 2020-02-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20200226_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='document',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.ManyToManyField(blank=True, to='posts.Topic'),
        ),
    ]
