# Generated by Django 3.0.3 on 2020-02-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20200226_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='created_time',
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
