# Generated by Django 3.0.3 on 2020-02-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20200228_0430'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='uid',
            field=models.CharField(default='parent', max_length=15),
        ),
    ]
