# Generated by Django 3.0.3 on 2020-03-14 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_post_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
