# Generated by Django 3.0.3 on 2020-03-14 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_post_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.Post')),
                ('file', models.FileField(upload_to='pdfs')),
            ],
            bases=('posts.post',),
        ),
    ]
