# Generated by Django 3.0.3 on 2020-03-15 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_auto_20200315_0332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date_posted',
        ),
    ]
