# Generated by Django 3.0.3 on 2020-03-19 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0030_auto_20200317_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('views', models.IntegerField(default=0)),
                ('source', models.URLField(blank=True)),
                ('pdf_file', models.FileField(upload_to='resources/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ManyToManyField(blank=True, to='posts.Topic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
