# Generated by Django 3.0.3 on 2020-03-19 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0031_auto_20200319_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='lower_age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdf',
            name='upper_age',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pdf',
            name='pdf_file',
            field=models.FileField(upload_to='resources/pdfs/'),
        ),
    ]
