# Generated by Django 3.0.3 on 2020-03-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0034_auto_20200319_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
