# Generated by Django 3.0.3 on 2020-03-31 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0037_auto_20200315_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('views', models.IntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
                ('source', models.URLField(blank=True)),
                ('lower_age', models.IntegerField(blank=True)),
                ('upper_age', models.IntegerField(blank=True)),
                ('video_file', models.FileField(upload_to='resources/videos/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL)),
                ('topics', models.ManyToManyField(blank=True, to='posts.Topic')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
