# Generated by Django 3.0.3 on 2020-04-02 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0039_auto_20200402_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='topics',
            field=models.ManyToManyField(blank=True, null=True, to='posts.Topic'),
        ),
        migrations.AlterField(
            model_name='post',
            name='topics',
            field=models.ManyToManyField(blank=True, null=True, to='posts.Topic'),
        ),
        migrations.AlterField(
            model_name='video',
            name='topics',
            field=models.ManyToManyField(blank=True, null=True, to='posts.Topic'),
        ),
    ]
