# Generated by Django 3.0.3 on 2020-04-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0040_auto_20200402_0221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_file',
        ),
        migrations.AddField(
            model_name='video',
            name='videoId',
            field=models.CharField(default='heh', max_length=150),
            preserve_default=False,
        ),
    ]
