# Generated by Django 3.0.3 on 2020-03-03 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200219_0641'),
    ]

    operations = [
        migrations.DeleteModel(
            name='news',
        ),
    ]
