# Generated by Django 3.0.3 on 2020-03-30 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_delete_news'),
    ]

    operations = [
    ]
