# Generated by Django 2.1.7 on 2020-03-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default='default', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='default', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='profession',
            field=models.CharField(default='default', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile'),
        ),
    ]
