# Generated by Django 2.1.7 on 2020-03-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default='default', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='default', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='profession',
            field=models.CharField(default='default', max_length=200),
        ),
    ]
