# Generated by Django 3.0.3 on 2020-02-28 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200227_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='default', max_length=20),
        ),
    ]
