# Generated by Django 2.1.3 on 2020-03-30 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200303_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='children',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Children',
        ),
    ]
